version: '3.3'

services:

    db:
        image: mysql:latest
        ports:
          - 3306:3306
        environment:
            MYSQL_DATABASE: sakila
            MYSQL_ROOT_PASSWORD: root
      
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
    
    app:                       
      build:
        context: .                          
        dockerfile: Dockerfile          
      ports:
        - "8080:8080"                     
      restart: always    
      depends_on:                           
        - db                               